<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { font-family: DejaVu Sans, sans-serif; }
  body { margin: 0; padding: 20px; font-size: 10px; }
  .header { border-bottom: 3px solid #0B3D91; padding-bottom: 10px; margin-bottom: 15px; }
  .logo { width: 40px; height: 40px; background: #D4AF37; color: #0B3D91; border-radius: 50%; text-align: center; line-height: 40px; font-weight: bold; font-size: 18px; display: inline-block; vertical-align: middle; }
  .school { display: inline-block; margin-left: 10px; vertical-align: middle; }
  .school-name { font-size: 18px; font-weight: bold; color: #0B3D91; }
  .school-tag { font-size: 8px; letter-spacing: 2px; color: #D4AF37; font-weight: bold; }
  .title { text-align: right; font-size: 16px; font-weight: bold; color: #0B3D91; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #0B3D91; color: white; padding: 6px 4px; text-align: center; font-size: 10px; }
  td { border: 1px solid #e5e7eb; padding: 6px 4px; text-align: center; font-size: 9px; }
  td.period { background: #f3f4f6; font-weight: bold; color: #0B3D91; }
  .subject { font-weight: bold; color: #0B3D91; font-size: 9px; }
  .teacher { color: #6b7280; font-size: 8px; margin-top: 2px; }
  .break { background: #fef3c7; color: #92400e; font-weight: bold; }
  .lunch { background: #dbeafe; color: #1e40af; font-weight: bold; }
  .footer { margin-top: 20px; padding-top: 8px; border-top: 2px solid #D4AF37; text-align: center; color: #6b7280; font-size: 8px; }
</style>
</head>
<body>

<div class="header">
  <div style="float:left;">
    <span class="logo">M</span>
    <span class="school">
      <div class="school-name">MARELL ACADEMY</div>
      <div class="school-tag">EMPOWERING TOMORROW'S LEADERS</div>
    </span>
  </div>
  <div style="float:right;">
    <div class="title">CLASS TIMETABLE</div>
    <div style="color:#6b7280;font-size:10px;">{{ $class->label() }}</div>
    <div style="color:#6b7280;font-size:9px;">{{ now()->format('d M Y') }}</div>
  </div>
  <div style="clear:both;"></div>
</div>

<table>
  <thead>
    <tr>
      <th style="width:60px;">PERIOD</th>
      <th>MONDAY</th>
      <th>TUESDAY</th>
      <th>WEDNESDAY</th>
      <th>THURSDAY</th>
      <th>FRIDAY</th>
    </tr>
  </thead>
  <tbody>
    @php $times = [1=>'08:00',2=>'08:40',3=>'09:20',4=>'10:20',5=>'11:00',6=>'11:40',7=>'14:00',8=>'14:40']; @endphp
    @for ($p = 1; $p <= 8; $p++)
      @if ($p === 4)
        <tr><td class="period">10:00</td><td colspan="5" class="break">☕ SHORT BREAK (10:00 – 10:20)</td></tr>
      @endif
      @if ($p === 7)
        <tr><td class="period">12:20</td><td colspan="5" class="lunch">🍽️ LUNCH (12:20 – 14:00)</td></tr>
      @endif
      <tr>
        <td class="period">{{ $times[$p] }}<br>P{{ $p }}</td>
        @foreach (['Mon','Tue','Wed','Thu','Fri'] as $d)
          @php $slot = $grid[$d][$p] ?? null; @endphp
          <td>
            @if ($slot)
              <div class="subject">{{ $slot->subject }}</div>
              <div class="teacher">{{ $slot->teacher->name ?? '—' }}</div>
            @else
              —
            @endif
          </td>
        @endforeach
      </tr>
    @endfor
  </tbody>
</table>

<div class="footer">
  Marell Academy · Kanduyi Road, Bungoma · +254 700 000 000 · info@marell.ac.ke<br>
  Generated by Jenga Web School OS · {{ now()->format('d M Y H:i') }}
</div>

</body>
</html>
